# Generated by Django 3.2 on 2021-06-28 20:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amphures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name_th', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_name_account', models.CharField(blank=True, max_length=255)),
                ('bank_number', models.CharField(blank=True, max_length=255)),
                ('bank_telephone', models.CharField(blank=True, max_length=255)),
                ('bank_image', models.ImageField(blank=True, null=True, upload_to='bank')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ชื่อ',
                'verbose_name_plural': 'ธนาคาร',
                'db_table': 'Bank',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'รหัสตะกร้า',
                'verbose_name_plural': 'ตะกร้า',
                'db_table': 'cart',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'หมวดหมู่สินค้า',
                'verbose_name_plural': 'ข้อมูลประเภทสินค้า',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Customer_contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(blank=True, max_length=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('amphures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.amphures')),
            ],
        ),
        migrations.CreateModel(
            name='Geographies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=store.models.random_number, max_length=255, unique=True)),
                ('costtotal', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer', models.CharField(blank=True, max_length=50, null=True)),
                ('transfer_image', models.ImageField(blank=True, default=None, null=True, upload_to='slip')),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.bank')),
                ('customer_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer_contract')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[('NEW', 'รอการชำระเงิน'), ('PAID', 'ชำระเงินแล้ว'), ('AWAITING SHIPMENT', 'รอการจัดส่ง'), ('DELIVERED', 'จัดส่งแล้ว')], default='NEW', max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'สถานะ',
                'verbose_name_plural': 'สถานะสินค้า',
                'db_table': 'OrderStatus',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, max_length=255)),
                ('payment_image', models.ImageField(blank=True, null=True, upload_to='payment')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ประเภท',
                'verbose_name_plural': 'ประเภทการชำระเงิน',
                'db_table': 'PaymentType',
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name_th', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('geography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.geographies')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
                ('sub_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='product')),
                ('stock', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'ข้อมูลสินค้า',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
            options={
                'db_table': 'OrderItem',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='orderstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orderstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='paymenttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.paymenttype'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('zip_code', models.IntegerField()),
                ('amphure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.amphures')),
            ],
        ),
        migrations.AddField(
            model_name='customer_contract',
            name='districts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.districts'),
        ),
        migrations.AddField(
            model_name='customer_contract',
            name='provinces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.provinces'),
        ),
        migrations.AddField(
            model_name='customer_contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='store.product')),
            ],
            options={
                'verbose_name': 'ข้อมูลสินค้า',
                'verbose_name_plural': 'รายการสินค้าในตะกร้า',
                'db_table': 'cartItem',
            },
        ),
        migrations.AddField(
            model_name='amphures',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.provinces'),
        ),
    ]
