# Generated by Django 3.2 on 2021-06-28 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_contract',
            options={'verbose_name_plural': 'ข้อมูลติดต่อลูกค้า'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'รายการสั้่งซื้อ'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('order',), 'verbose_name_plural': 'สินค้าในรายการสั้่งซื้อ'},
        ),
        migrations.AddField(
            model_name='order',
            name='charge',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='credit_email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.bank'),
        ),
    ]
